# Generated by Django 3.2.7 on 2021-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AlterField(
            model_name='people',
            name='personal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
