# Generated by Django 3.2.7 on 2021-12-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20211228_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='personal_id',
        ),
        migrations.AddField(
            model_name='people',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
