# Generated by Django 3.2.7 on 2021-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20211228_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AddField(
            model_name='people',
            name='personal_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
